// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xvibrato.h"

extern XVibrato_Config XVibrato_ConfigTable[];

XVibrato_Config *XVibrato_LookupConfig(u16 DeviceId) {
	XVibrato_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XVIBRATO_NUM_INSTANCES; Index++) {
		if (XVibrato_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XVibrato_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XVibrato_Initialize(XVibrato *InstancePtr, u16 DeviceId) {
	XVibrato_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XVibrato_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XVibrato_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

