// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xvibrato.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XVibrato_CfgInitialize(XVibrato *InstancePtr, XVibrato_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XVibrato_Set_delay(XVibrato *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVibrato_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XVIBRATO_CTRL_BUS_ADDR_DELAY_DATA, Data);
}

u32 XVibrato_Get_delay(XVibrato *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVibrato_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XVIBRATO_CTRL_BUS_ADDR_DELAY_DATA);
    return Data;
}

void XVibrato_Set_depth(XVibrato *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVibrato_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XVIBRATO_CTRL_BUS_ADDR_DEPTH_DATA, Data);
}

u32 XVibrato_Get_depth(XVibrato *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVibrato_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XVIBRATO_CTRL_BUS_ADDR_DEPTH_DATA);
    return Data;
}

