// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _scaled_fixed2ieee_HH_
#define _scaled_fixed2ieee_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "vibrato_mux_42_32_1.h"

namespace ap_rtl {

struct scaled_fixed2ieee : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<63> > in_V;
    sc_in< sc_lv<12> > prescale;
    sc_out< sc_lv<64> > ap_return;


    // Module declarations
    scaled_fixed2ieee(sc_module_name name);
    SC_HAS_PROCESS(scaled_fixed2ieee);

    ~scaled_fixed2ieee();

    sc_trace_file* mVcdFile;

    vibrato_mux_42_32_1<1,1,32,32,32,32,2,32>* vibrato_mux_42_32_1_U1;
    vibrato_mux_42_32_1<1,1,32,32,32,32,2,32>* vibrato_mux_42_32_1_U2;
    sc_signal< sc_lv<8> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > i_1_fu_274_p2;
    sc_signal< sc_lv<2> > i_1_reg_797;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<6> > Hi_assign_fu_288_p2;
    sc_signal< sc_lv<6> > Hi_assign_reg_802;
    sc_signal< sc_lv<1> > exitcond1_fu_268_p2;
    sc_signal< sc_lv<6> > Lo_assign_fu_294_p2;
    sc_signal< sc_lv<6> > Lo_assign_reg_808;
    sc_signal< sc_lv<1> > tmp_65_fu_300_p2;
    sc_signal< sc_lv<1> > tmp_65_reg_815;
    sc_signal< sc_lv<6> > tmp_68_fu_306_p2;
    sc_signal< sc_lv<6> > tmp_68_reg_822;
    sc_signal< sc_lv<32> > p_Result_46_fu_323_p5;
    sc_signal< sc_lv<32> > p_Result_46_reg_827;
    sc_signal< sc_lv<16> > tmp_79_fu_402_p1;
    sc_signal< sc_lv<16> > tmp_79_reg_832;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > out_bits_2_V_1_fu_461_p3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > out_bits_2_V_6_fu_477_p3;
    sc_signal< sc_lv<32> > out_bits_2_V_8_fu_485_p3;
    sc_signal< sc_lv<3> > i_2_fu_499_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > c_3_fu_572_p3;
    sc_signal< sc_lv<1> > exitcond_fu_493_p2;
    sc_signal< sc_lv<32> > c_3_3_fu_588_p3;
    sc_signal< sc_lv<32> > c_3_5_fu_596_p3;
    sc_signal< sc_lv<32> > c_3_6_fu_612_p3;
    sc_signal< sc_lv<1> > tmp_81_fu_620_p3;
    sc_signal< sc_lv<1> > tmp_81_reg_880;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<3> > i_3_fu_628_p2;
    sc_signal< sc_lv<3> > i_3_reg_884;
    sc_signal< sc_lv<32> > sh_assign_fu_638_p6;
    sc_signal< sc_lv<32> > sh_assign_reg_889;
    sc_signal< sc_lv<1> > isNeg_reg_896;
    sc_signal< sc_lv<32> > tmp_30_fu_660_p2;
    sc_signal< sc_lv<32> > tmp_30_reg_902;
    sc_signal< sc_lv<32> > shift_2_fu_666_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<63> > in_shift_V_fu_692_p3;
    sc_signal< sc_lv<12> > tmp_35_fu_704_p2;
    sc_signal< sc_lv<12> > tmp_35_reg_922;
    sc_signal< sc_lv<1> > tmp_34_fu_699_p2;
    sc_signal< sc_lv<1> > tmp_37_fu_709_p2;
    sc_signal< sc_lv<1> > tmp_37_reg_927;
    sc_signal< sc_lv<32> > out_bits_2_V_s_reg_108;
    sc_signal< sc_lv<32> > out_bits_1_V_s_reg_120;
    sc_signal< sc_lv<32> > out_bits_2_V_7_reg_132;
    sc_signal< sc_lv<2> > i_reg_144;
    sc_signal< sc_lv<32> > c_2_s_reg_156;
    sc_signal< sc_lv<32> > c_3_1_reg_168;
    sc_signal< sc_lv<32> > c_3_4_reg_180;
    sc_signal< sc_lv<32> > c_3_s_reg_192;
    sc_signal< sc_lv<3> > i1_reg_204;
    sc_signal< sc_lv<63> > in_shift_reg_215;
    sc_signal< sc_lv<32> > shift_reg_225;
    sc_signal< sc_lv<3> > i2_reg_237;
    sc_signal< sc_lv<63> > p_Val2_s_reg_248;
    sc_signal< sc_lv<32> > shift_1_reg_258;
    sc_signal< sc_lv<6> > tmp_s_fu_280_p3;
    sc_signal< sc_lv<15> > tmp_64_fu_312_p1;
    sc_signal< sc_lv<16> > tmp_fu_315_p3;
    sc_signal< sc_lv<6> > tmp_67_fu_344_p2;
    sc_signal< sc_lv<6> > tmp_69_fu_348_p2;
    sc_signal< sc_lv<63> > tmp_66_fu_335_p4;
    sc_signal< sc_lv<6> > tmp_70_fu_352_p3;
    sc_signal< sc_lv<6> > tmp_72_fu_365_p3;
    sc_signal< sc_lv<6> > tmp_73_fu_370_p2;
    sc_signal< sc_lv<63> > tmp_71_fu_359_p3;
    sc_signal< sc_lv<63> > tmp_74_fu_376_p1;
    sc_signal< sc_lv<63> > tmp_75_fu_380_p1;
    sc_signal< sc_lv<63> > tmp_76_fu_384_p2;
    sc_signal< sc_lv<63> > tmp_77_fu_390_p2;
    sc_signal< sc_lv<63> > p_Result_s_fu_396_p2;
    sc_signal< sc_lv<1> > sel_tmp_fu_406_p2;
    sc_signal< sc_lv<1> > sel_tmp9_fu_420_p2;
    sc_signal< sc_lv<32> > out_bits_2_V_fu_412_p3;
    sc_signal< sc_lv<32> > out_bits_2_V_9_fu_426_p3;
    sc_signal< sc_lv<17> > tmp_28_fu_434_p3;
    sc_signal< sc_lv<32> > p_Result_45_fu_441_p5;
    sc_signal< sc_lv<32> > out_bits_2_V_4_fu_453_p3;
    sc_signal< sc_lv<32> > out_bits_2_V_5_fu_469_p3;
    sc_signal< sc_lv<2> > tmp_80_fu_505_p1;
    sc_signal< sc_lv<32> > p_Val2_67_fu_509_p6;
    sc_signal< sc_lv<32> > p_Result_47_fu_522_p4;
    sc_signal< sc_lv<1> > sel_tmp5_fu_552_p2;
    sc_signal< sc_lv<1> > sel_tmp4_fu_546_p2;
    sc_signal< sc_lv<1> > sel_tmp3_fu_540_p2;
    sc_signal< sc_lv<32> > c_3_8_fu_532_p3;
    sc_signal< sc_lv<1> > or_cond_fu_558_p2;
    sc_signal< sc_lv<32> > newSel_fu_564_p3;
    sc_signal< sc_lv<32> > c_3_2_fu_580_p3;
    sc_signal< sc_lv<32> > newSel2_fu_604_p3;
    sc_signal< sc_lv<2> > sh_assign_fu_638_p5;
    sc_signal< sc_lv<32> > sh_assign_1_fu_671_p3;
    sc_signal< sc_lv<63> > tmp_31_fu_676_p1;
    sc_signal< sc_lv<63> > tmp_33_fu_686_p2;
    sc_signal< sc_lv<63> > tmp_32_fu_680_p2;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > tmp_37_cast_fu_714_p1;
    sc_signal< sc_lv<32> > newexp_fu_717_p2;
    sc_signal< sc_lv<1> > tmp_84_fu_723_p3;
    sc_signal< sc_lv<1> > or_cond_43_fu_731_p2;
    sc_signal< sc_lv<52> > phitmp2_fu_740_p4;
    sc_signal< sc_lv<11> > tmp_85_fu_736_p1;
    sc_signal< sc_lv<11> > out_exp_V_fu_758_p3;
    sc_signal< sc_lv<52> > p_Val2_68_fu_750_p3;
    sc_signal< sc_lv<64> > p_Result_48_fu_766_p4;
    sc_signal< sc_lv<64> > result_write_assign_fu_776_p1;
    sc_signal< sc_lv<64> > ap_return_preg;
    sc_signal< sc_lv<8> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_ST_fsm_state1;
    static const sc_lv<8> ap_ST_fsm_state2;
    static const sc_lv<8> ap_ST_fsm_state3;
    static const sc_lv<8> ap_ST_fsm_state4;
    static const sc_lv<8> ap_ST_fsm_state5;
    static const sc_lv<8> ap_ST_fsm_state6;
    static const sc_lv<8> ap_ST_fsm_state7;
    static const sc_lv<8> ap_ST_fsm_state8;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<6> ap_const_lv6_3E;
    static const sc_lv<6> ap_const_lv6_2F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<63> ap_const_lv63_7FFFFFFFFFFFFFFF;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<12> ap_const_lv12_3FF;
    static const sc_lv<63> ap_const_lv63_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_3D;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Hi_assign_fu_288_p2();
    void thread_Lo_assign_fu_294_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_c_3_2_fu_580_p3();
    void thread_c_3_3_fu_588_p3();
    void thread_c_3_5_fu_596_p3();
    void thread_c_3_6_fu_612_p3();
    void thread_c_3_8_fu_532_p3();
    void thread_c_3_fu_572_p3();
    void thread_exitcond1_fu_268_p2();
    void thread_exitcond_fu_493_p2();
    void thread_i_1_fu_274_p2();
    void thread_i_2_fu_499_p2();
    void thread_i_3_fu_628_p2();
    void thread_in_shift_V_fu_692_p3();
    void thread_newSel2_fu_604_p3();
    void thread_newSel_fu_564_p3();
    void thread_newexp_fu_717_p2();
    void thread_or_cond_43_fu_731_p2();
    void thread_or_cond_fu_558_p2();
    void thread_out_bits_2_V_1_fu_461_p3();
    void thread_out_bits_2_V_4_fu_453_p3();
    void thread_out_bits_2_V_5_fu_469_p3();
    void thread_out_bits_2_V_6_fu_477_p3();
    void thread_out_bits_2_V_8_fu_485_p3();
    void thread_out_bits_2_V_9_fu_426_p3();
    void thread_out_bits_2_V_fu_412_p3();
    void thread_out_exp_V_fu_758_p3();
    void thread_p_Result_45_fu_441_p5();
    void thread_p_Result_46_fu_323_p5();
    void thread_p_Result_47_fu_522_p4();
    void thread_p_Result_48_fu_766_p4();
    void thread_p_Result_s_fu_396_p2();
    void thread_p_Val2_68_fu_750_p3();
    void thread_phitmp2_fu_740_p4();
    void thread_result_write_assign_fu_776_p1();
    void thread_sel_tmp3_fu_540_p2();
    void thread_sel_tmp4_fu_546_p2();
    void thread_sel_tmp5_fu_552_p2();
    void thread_sel_tmp9_fu_420_p2();
    void thread_sel_tmp_fu_406_p2();
    void thread_sh_assign_1_fu_671_p3();
    void thread_sh_assign_fu_638_p5();
    void thread_shift_2_fu_666_p2();
    void thread_tmp_28_fu_434_p3();
    void thread_tmp_30_fu_660_p2();
    void thread_tmp_31_fu_676_p1();
    void thread_tmp_32_fu_680_p2();
    void thread_tmp_33_fu_686_p2();
    void thread_tmp_34_fu_699_p2();
    void thread_tmp_35_fu_704_p2();
    void thread_tmp_37_cast_fu_714_p1();
    void thread_tmp_37_fu_709_p2();
    void thread_tmp_64_fu_312_p1();
    void thread_tmp_65_fu_300_p2();
    void thread_tmp_66_fu_335_p4();
    void thread_tmp_67_fu_344_p2();
    void thread_tmp_68_fu_306_p2();
    void thread_tmp_69_fu_348_p2();
    void thread_tmp_70_fu_352_p3();
    void thread_tmp_71_fu_359_p3();
    void thread_tmp_72_fu_365_p3();
    void thread_tmp_73_fu_370_p2();
    void thread_tmp_74_fu_376_p1();
    void thread_tmp_75_fu_380_p1();
    void thread_tmp_76_fu_384_p2();
    void thread_tmp_77_fu_390_p2();
    void thread_tmp_79_fu_402_p1();
    void thread_tmp_80_fu_505_p1();
    void thread_tmp_81_fu_620_p3();
    void thread_tmp_84_fu_723_p3();
    void thread_tmp_85_fu_736_p1();
    void thread_tmp_fu_315_p3();
    void thread_tmp_s_fu_280_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
